In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=['the glas of milk',
      'the glass of juice',
      'i am a good boy',
      'i am a bad developer',
      'understand the meaning of words',
      'your videos are good ']

In [4]:
sent

['the glas of milk',
 'the glass of juice',
 'i am a good boy',
 'i am a bad developer',
 'understand the meaning of words',
 'your videos are good ']

In [5]:
voc_size= 10000

In [6]:
one_hot_repr=[one_hot(words,voc_size) for words in sent] # this will give us the one hot representation of the words in the sentences

In [7]:
one_hot_repr

[[627, 4018, 6110, 7123],
 [627, 220, 6110, 5786],
 [6001, 8033, 1418, 2038, 9735],
 [6001, 8033, 1418, 379, 1433],
 [1518, 627, 2875, 6110, 1022],
 [8632, 4933, 3200, 2038]]

In [8]:
## word emding layar 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
# pad_sequences is used to make the length of all the sentences equal by adding 0's in the beginning of the sentences which are smaller in length than the maximum length sentence.
# otherwise the model will not be able to process the sentences of different lengths.

In [9]:
import numpy as np


In [10]:
set_length =8 
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=set_length)
print(embedded_docs )
# here we have used padding='pre' which means that the 0's will be added in the beginning of the sentences which are smaller in length than the maximum length sentence.

[[   0    0    0    0  627 4018 6110 7123]
 [   0    0    0    0  627  220 6110 5786]
 [   0    0    0 6001 8033 1418 2038 9735]
 [   0    0    0 6001 8033 1418  379 1433]
 [   0    0    0 1518  627 2875 6110 1022]
 [   0    0    0    0 8632 4933 3200 2038]]


In [11]:
# feature representation of the sentences
dim= 10 


In [12]:
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=set_length))# here we have used voc_size as the input dimension which is the size of the vocabulary, dim as the output dimension which is the size of the embedding vector and set_length as the input length which is the length of the sentences. 
model.compile('adam','mse') # here we have used adam as the optimizer and mse as the loss function.

/Users/harshvardhansingh/Downloads/ml_practice/venv/lib/python3.9/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.predict(embedded_docs) # this will give us the feature representation of the sentences in the form of a 3D array. The shape of the array will be (number of sentences, length of sentences, size of embedding vector).

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


array([[[-0.04020875, -0.03907349, -0.045698  , -0.04752257,
         -0.01894585,  0.02253535,  0.04393813,  0.01986459,
          0.03700541, -0.0217625 ],
        [-0.04020875, -0.03907349, -0.045698  , -0.04752257,
         -0.01894585,  0.02253535,  0.04393813,  0.01986459,
          0.03700541, -0.0217625 ],
        [-0.04020875, -0.03907349, -0.045698  , -0.04752257,
         -0.01894585,  0.02253535,  0.04393813,  0.01986459,
          0.03700541, -0.0217625 ],
        [-0.04020875, -0.03907349, -0.045698  , -0.04752257,
         -0.01894585,  0.02253535,  0.04393813,  0.01986459,
          0.03700541, -0.0217625 ],
        [-0.03972533, -0.04021829,  0.0197506 ,  0.02789188,
         -0.00076851,  0.00845953,  0.02492925, -0.03223544,
         -0.04596356,  0.04183852],
        [ 0.0420006 ,  0.02784128,  0.03490175,  0.04109589,
          0.02954492,  0.04173343,  0.00757708, -0.00105707,
         -0.01171737,  0.03024948],
        [ 0.04044156, -0.0171659 ,  0.01778311, -0.0

In [21]:
model.predict([0,0,0,0,0,0,0,0]) # this will give us the feature representation of the sentences in the form of a 3D array. The shape of the array will be (number of sentences, length of sentences, size of embedding vector).

ValueError: Unrecognized data type: x=[0, 0, 0, 0, 0, 0, 0, 0] (of type <class 'list'>)